### ISSUE TITLE
Undefined offset category filter

### ISSUE THREAD

**Issue by rimacher** [CLAMP-IT/moodle-blocks_filtered_course_list#100] opened 2018-03-26 07:26 UTC
Hi,

I tried using the category filter and if I use anything other than the lowest level category I get the error:

Notice: Undefined offset: XXX in ....../moodle/blocks/filtered_course_list/locallib.php on line 224

Our category structure is: year>semester>faculty>department

If I use the department ID it works. Anything else- I get this error with different category IDs.

**Comment by kwiliarty** [comment] 2018-03-26 10:30
Thanks for the heads up. Let me see what I can find.

**Comment by kwiliarty** [comment] 2018-03-26 10:40
I'm not able to reproduce the problem. To help me troubleshoot could you:

- Let me know your Moodle version
- Let me know your Filtered Course List version
- Paste in your filter configuration

**Comment by rimacher** [comment] 2018-03-27 07:09
We use moodle 3.4.1 and the plugin version is v3.3.3 (2018012400).

I tried different filter configurations and none works:

category | collapsed | 0 | 0
category | collapsed | 999 (department id) | 0
category | collapsed | 999 (department id) | 1

**Comment by rimacher** [comment] 2018-03-28 09:33
The settings are on default. When I use a faculty id I get the following errors. Those IDs are of other departments in the same faculty.

![28-03-2018 12-24-01](https://user-images.githubusercontent.com/16016842/38020899-1c0dfba8-3284-11e8-9f95-22697034d480.png)

**Comment by kwiliarty** [comment] 2018-03-28 19:13
I've built myself a Moodle 3.4.1 to test against, and I've tried removing the default category in case that was somehow playing a role, but I am still unable to reproduce the problem. Can you tell me which PHP version you are using, and which database (MySQL, PostgreSQL, ...)? 

I would also be interested to know how you are creating categories. Since you have so many, I wonder if you are using some kind of automated process. Do the category pages show up fine when you go to them in a browser? For instance, if you go to `/course/management.php?categoryid=1240` do you get the normal category page?

Sorry to have more questions; I'd really love to get to the bottom of this error. Thanks for your patience and help.

**Comment by rimacher** [comment] 2018-03-29 05:28
Thank you for trying to figure it out. We use PHP Version 7.2.3 and 5.5.56-MariaDB.

We do have a custom script for creating categories but I get the normal category page.

Also the only way the department filter works is when "Category rubric template" is set to "NAME". "ANCESTRY" gives me offset errors.

I'm able to use the regex filter to filter courses by year but we got requests for semester filtering as well. If it's connected to our custom category structure/creation it can't be helped.

**Comment by kwiliarty** [comment] 2018-03-29 11:17
Knowing that "ANCESTRY" and "NAME" behave differently will definitely help me narrow things down, though I still am unable to reproduce the problem. Does "PARENT" work?

I'm getting an idea for something to try. Do you have access to your database and/or code? I'm just wondering if you would be able to run some simple SELECT queries or try out some alternative code.

**Comment by kwiliarty** [comment] 2018-04-06 13:59
Following up... If you do have the capability of testing a code modification you might try this:  

In the `/blocks/filtered_course_list/locallib.php` file replace the following two lines (223-4):

```php
$ancestors = coursecat::make_categories_list('', 0, $separator);
$ancestry = $ancestors[$category->id];
```

With this one line:

```php
$ancestry = $category->get_nested_name(false, $separator);
```

And then please let me know if that makes a difference. If it does I would include it in a new release. It certainly seems to offer better performance on my installation with thousands of categories, but since I cannot reproduce the problem you are seeing I cannot tell whether it will resolve it or not.

**Comment by kwiliarty** [comment] 2018-04-06 16:45
I'm going to push a change like the one I suggest above. At the very least, it is more efficient, and so I should use it anyway. It will close this issue, but I realize that it may not actually solve the problem you are seeing, so if it does not you should feel free to reopen this issue.

**Closed** 2018-04-06 16:45 UTC

**Comment by rimacher** [comment] 2018-04-08 06:28
Unfortunately it didn't solve my problem.

**Comment by kwiliarty** [comment] 2018-04-08 13:56
I'm sorry to hear that. I'm not sure what else to try. It's hard for me to troubleshoot when I can't reproduce the problem.

**Comment by kwiliarty** [comment] 2018-04-16 13:27
See #102 for an important follow-up to this issue.
